services:
  backend:
    build: food-truck-server
    restart: always    
    ports:
      - 8080:8080
    networks:
      - react-spring
  frontend:
    build:
      context: food-truck-client
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./food-truck-client/src:/code/src
      - /food-truck-client/node_modules
    networks:
      - react-spring    
networks:
  react-spring: {}