/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContextErrorCauseStackTrace } from './context-error-cause-stack-trace';
/**
 * 
 * @export
 * @interface ContextErrorCauseSuppressed
 */
export interface ContextErrorCauseSuppressed {
    /**
     * 
     * @type {Array<ContextErrorCauseStackTrace>}
     * @memberof ContextErrorCauseSuppressed
     */
    stackTrace?: Array<ContextErrorCauseStackTrace>;
    /**
     * 
     * @type {string}
     * @memberof ContextErrorCauseSuppressed
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ContextErrorCauseSuppressed
     */
    localizedMessage?: string;
}
