/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ContextErrorCauseStackTrace
 */
export interface ContextErrorCauseStackTrace {
    /**
     * 
     * @type {string}
     * @memberof ContextErrorCauseStackTrace
     */
    classLoaderName?: string;
    /**
     * 
     * @type {string}
     * @memberof ContextErrorCauseStackTrace
     */
    moduleName?: string;
    /**
     * 
     * @type {string}
     * @memberof ContextErrorCauseStackTrace
     */
    moduleVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof ContextErrorCauseStackTrace
     */
    methodName?: string;
    /**
     * 
     * @type {string}
     * @memberof ContextErrorCauseStackTrace
     */
    fileName?: string;
    /**
     * 
     * @type {number}
     * @memberof ContextErrorCauseStackTrace
     */
    lineNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof ContextErrorCauseStackTrace
     */
    className?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ContextErrorCauseStackTrace
     */
    nativeMethod?: boolean;
}
