/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContextErrorCauseStackTrace } from './context-error-cause-stack-trace';
import { ContextErrorCauseSuppressed } from './context-error-cause-suppressed';
/**
 * 
 * @export
 * @interface ContextErrorCause
 */
export interface ContextErrorCause {
    /**
     * 
     * @type {Array<ContextErrorCauseStackTrace>}
     * @memberof ContextErrorCause
     */
    stackTrace?: Array<ContextErrorCauseStackTrace>;
    /**
     * 
     * @type {string}
     * @memberof ContextErrorCause
     */
    message?: string;
    /**
     * 
     * @type {Array<ContextErrorCauseSuppressed>}
     * @memberof ContextErrorCause
     */
    suppressed?: Array<ContextErrorCauseSuppressed>;
    /**
     * 
     * @type {string}
     * @memberof ContextErrorCause
     */
    localizedMessage?: string;
}
