/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Context } from './context';
import { ContextView } from './context-view';
import { Scope } from './scope';
/**
 * 
 * @export
 * @interface Observation
 */
export interface Observation {
    /**
     * 
     * @type {Context}
     * @memberof Observation
     */
    context?: Context;
    /**
     * 
     * @type {boolean}
     * @memberof Observation
     */
    noop?: boolean;
    /**
     * 
     * @type {ContextView}
     * @memberof Observation
     */
    contextView?: ContextView;
    /**
     * 
     * @type {Scope}
     * @memberof Observation
     */
    enclosingScope?: Scope;
}
