/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContextView } from './context-view';
import { Scope } from './scope';
/**
 * 
 * @export
 * @interface ObservationView
 */
export interface ObservationView {
    /**
     * 
     * @type {Scope}
     * @memberof ObservationView
     */
    enclosingScope?: Scope;
    /**
     * 
     * @type {ContextView}
     * @memberof ObservationView
     */
    contextView?: ContextView;
}
