/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Observation } from './observation';
import { Scope } from './scope';
/**
 * 
 * @export
 * @interface ObservationRegistry
 */
export interface ObservationRegistry {
    /**
     * 
     * @type {Observation}
     * @memberof ObservationRegistry
     */
    currentObservation?: Observation;
    /**
     * 
     * @type {boolean}
     * @memberof ObservationRegistry
     */
    noop?: boolean;
    /**
     * 
     * @type {Scope}
     * @memberof ObservationRegistry
     */
    currentObservationScope?: Scope;
}
