/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FoodTruckPermit } from './food-truck-permit';
import { PageableObject } from './pageable-object';
import { SortObject } from './sort-object';
/**
 * 
 * @export
 * @interface PageImplFoodTruckPermit
 */
export interface PageImplFoodTruckPermit {
    /**
     * 
     * @type {Array<FoodTruckPermit>}
     * @memberof PageImplFoodTruckPermit
     */
    content?: Array<FoodTruckPermit>;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageImplFoodTruckPermit
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageImplFoodTruckPermit
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageImplFoodTruckPermit
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageImplFoodTruckPermit
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageImplFoodTruckPermit
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageImplFoodTruckPermit
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageImplFoodTruckPermit
     */
    sort?: SortObject;
    /**
     * 
     * @type {number}
     * @memberof PageImplFoodTruckPermit
     */
    numberOfElements?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageImplFoodTruckPermit
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageImplFoodTruckPermit
     */
    empty?: boolean;
}
