/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClientHttpRequestFactory } from './client-http-request-factory';
import { ClientHttpRequestInitializer } from './client-http-request-initializer';
import { ClientHttpRequestInterceptor } from './client-http-request-interceptor';
import { ClientRequestObservationConvention } from './client-request-observation-convention';
import { HttpMessageConverterObject } from './http-message-converter-object';
import { ObservationRegistry } from './observation-registry';
import { ResponseErrorHandler } from './response-error-handler';
import { UriTemplateHandler } from './uri-template-handler';
/**
 * 
 * @export
 * @interface RestTemplate
 */
export interface RestTemplate {
    /**
     * 
     * @type {ClientHttpRequestFactory}
     * @memberof RestTemplate
     */
    requestFactory?: ClientHttpRequestFactory;
    /**
     * 
     * @type {Array<ClientHttpRequestInitializer>}
     * @memberof RestTemplate
     */
    clientHttpRequestInitializers?: Array<ClientHttpRequestInitializer>;
    /**
     * 
     * @type {Array<ClientHttpRequestInterceptor>}
     * @memberof RestTemplate
     */
    interceptors?: Array<ClientHttpRequestInterceptor>;
    /**
     * 
     * @type {Array<HttpMessageConverterObject>}
     * @memberof RestTemplate
     */
    messageConverters?: Array<HttpMessageConverterObject>;
    /**
     * 
     * @type {ResponseErrorHandler}
     * @memberof RestTemplate
     */
    errorHandler?: ResponseErrorHandler;
    /**
     * 
     * @type {UriTemplateHandler}
     * @memberof RestTemplate
     */
    uriTemplateHandler?: UriTemplateHandler;
    /**
     * 
     * @type {ObservationRegistry}
     * @memberof RestTemplate
     */
    observationRegistry?: ObservationRegistry;
    /**
     * 
     * @type {ClientRequestObservationConvention}
     * @memberof RestTemplate
     */
    observationConvention?: ClientRequestObservationConvention;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof RestTemplate
     */
    defaultUriVariables?: { [key: string]: any; };
}
